name: cross_platform_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.3
  flutter_secure_storage: ^9.2.4
  flutter_riverpod: ^3.0.3
  go_router: ^16.3.0
  path_provider: ^2.1.5
  freezed_annotation: ^3.1.0
  pool: ^1.5.2
  uuid: ^4.5.2
  file_picker: ^10.3.6
  path: ^1.9.1
  drift: ^2.29.0
  drift_flutter: ^0.2.7
  sqlite3_flutter_libs: ^0.5.40
  collection: ^1.19.1
  shared_preferences: ^2.5.3
  crypto: ^3.0.7
  local_file_id_service:
    path: plugins/local_file_id_service

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_lint: ^3.0.3
  custom_lint: ^0.8.0
  drift_dev: ^2.29.0
  build_runner: ^2.7.1

flutter:
  uses-material-design: true
